windfield:
  type: "StaticInSpaceAndTime"
  wind:
    params:
      TWA: 0.0
      TWS: 10.0
  field:
    vertices:
      - [0.0, 0.0]
      - [0.0, 100.0]
      - [100.0, 100.0]
      - [100.0, 0.0]
tzero: 0.0
tmax: 40.0
dt: 0.1
boats:
  alpha:
    polar_diagram:
      type: "Uniform"
      sog: 10.0
    init_coords: [10.0, 50.0]
    target_coords: [90.0, 50.0]
  beta:
    polar_diagram:
      type: "Uniform"
      sog: 5.0
    init_coords: [10.0, 10.0]
    target_coords: [90.0, 50.0]
